export default [
  {
    id: 1,
    kalkisSaati: "7:15",
    inisSaati: "13:00",
    kalkisYeri: "Istanbul/Ümraniye Dudulu",
    inisYeri: "Ankara/Otogarı",
    seferBilgileri: "5:45",
    fiyat: "110,00",
    ozellikler: "",
    koltuklar: {
      row1: [
        { id: "1", empty: true, selected: false, gender: "" },
        { id: "4", empty: false, selected: true, gender: "woman" },
        { id: "7", empty: true, selected: false, gender: "" },
        { id: "10", empty: true, selected: false, gender: "" },
        { id: "13", empty: true, selected: false, gender: "" },
        { id: "16", empty: true, selected: false, gender: "" },
        { id: "19", empty: true, selected: false, gender: "" },
      ],
      row2: [
        { id: "2", empty: false, selected: true, gender: "man" },
        { id: "3", empty: false, selected: true, gender: "woman" },
        { id: "5", empty: true, selected: false, gender: "" },
        { id: "6", empty: true, selected: false, gender: "" },
        { id: "8", empty: true, selected: false, gender: "" },
        { id: "9", empty: true, selected: false, gender: "" },
        { id: "11", empty: true, selected: false, gender: "" },
        { id: "12", empty: false, selected: true, gender: "man" },
        { id: "14", empty: true, selected: false, gender: "" },
        { id: "15", empty: true, selected: false, gender: "" },
        { id: "17", empty: true, selected: false, gender: "" },
        { id: "18", empty: true, selected: false, gender: "" },
        { id: "20", empty: true, selected: false, gender: "" },
        { id: "21", empty: true, selected: false, gender: "" },
      ],
    },
  },
  {
    id: 2,
    kalkisSaati: "8:00",
    inisSaati: "15:00",
    kalkisYeri: "Istanbul/Esenler Otogarı",
    inisYeri: "Ankara/Otogarı",
    seferBilgileri: "7:00",
    fiyat: "110,00",
    ozellikler: "",
    koltuklar: {
      row1: [
        { id: "1", empty: true, selected: false, gender: "" },
        { id: "4", empty: true, selected: false, gender: "" },
        { id: "7", empty: true, selected: false, gender: "" },
        { id: "10", empty: true, selected: false, gender: "" },
        { id: "13", empty: true, selected: false, gender: "" },
        { id: "16", empty: false, selected: true, gender: "woman" },
        { id: "19", empty: true, selected: false, gender: "" },
      ],
      row2: [
        { id: "2", empty: false, selected: true, gender: "man" },
        { id: "3", empty: false, selected: true, gender: "woman" },
        { id: "5", empty: true, selected: false, gender: "" },
        { id: "6", empty: true, selected: false, gender: "" },
        { id: "8", empty: true, selected: false, gender: "" },
        { id: "9", empty: true, selected: false, gender: "" },
        { id: "11", empty: true, selected: false, gender: "" },
        { id: "12", empty: false, selected: true, gender: "man" },
        { id: "14", empty: true, selected: false, gender: "" },
        { id: "15", empty: true, selected: false, gender: "" },
        { id: "17", empty: true, selected: false, gender: "" },
        { id: "18", empty: true, selected: false, gender: "" },
        { id: "20", empty: true, selected: false, gender: "" },
        { id: "21", empty: true, selected: false, gender: "" },
      ],
    },
  },
];
