import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: { flex: 1 },
  slideBar: { margin: 2 },
  slidePicture: { width: "100%", height: 250 },
  slideText: {
    width: "100%",
    opacity: 0.5,
    backgroundColor: "black",
    position: "absolute",
    bottom: 0,
    fontSize: 20,
    padding: 8,
    fontWeight: "bold",
    color: "white",
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
  },
  travelContainer: { flex: 1, padding: 5 },
  radioButtonContainer: { flexDirection: "row", alignItems: "center" },
  cityInput: {
    marginHorizontal: 5,
    marginVertical: 5,
    paddingStart: 15,
    borderRadius: 10,
    color: "black",
    borderWidth: 1,
    flexDirection: "row",
    alignItems: "center",
  },
  Input: {
    flexDirection: "row",
    alignItems: "center",
    marginHorizontal: 5,
    marginVertical: 5,
    paddingStart: 15,
    borderRadius: 10,
    color: "black",
    borderWidth: 1,
    padding: 16,
  },
  button: {
    marginHorizontal: 10,
    backgroundColor: "#f9a825",
    marginVertical: 10,
    padding: 10,
    alignItems: "center",
    borderRadius: 15,
  },
  buttonText: {
    color: "white",
    fontWeight: "bold",
    fontSize: 18,
  },
});
